/*
 * Copyright (c) 2007-2023, Marketo, Inc. All rights reserved.
 * See https://developers.marketo.com/MunchkinLicense.pdf for license terms
 * Marketo marketing automation web activity tracking script
 * Version: 165 r963
 */
 (function(k){if(!k.MunchkinTracker){var l=k.document,q=l.location,C=encodeURIComponent,y=!1,r=null,t=null,D=!1,u=null,E=[],v=function(b,a,c,d){try{var f=function(){try{c.apply(this,arguments)}catch(a){}};b.addEventListener?b.addEventListener(a,f,d||!1):b.attachEvent&&b.attachEvent("on"+a,f);E.push([b,a,f,d])}catch(e){}},W=function(b,a,c,d){try{b.removeEventListener?b.removeEventListener(a,c,d||!1):b.detachEvent&&b.detachEvent("on"+a,c)}catch(f){}},e=function(b){return"undefined"!==typeof b&&null!==
b},F=function(b,a){return b.className.match(RegExp("(\\s|^)"+a+"(\\s|$)"))},X=e(k.XMLHttpRequest)&&e((new k.XMLHttpRequest).withCredentials),s=function(b){var a=null,c;if(e(b))if(0===b.length)a="";else try{a=decodeURIComponent(b)}catch(d){c=b.indexOf("?");if(-1!==c)try{a=decodeURIComponent(b.substr(0,c))+b.substr(c)}catch(f){}e(a)||(a=String(b))}return a},G=function(b,a){var c={},d=e(a)?a:"=",f=b.split("&"),h=f.length,g,p,l;for(g=0;g<h;g+=1)p=f[g].split(d),e(p)&&1<p.length&&(l=p.shift(),p=p.join(d),
c[s(l)]=s(p));return c},H=function(b){try{var a=l.createElement("a");a.href=b;return G(a.search.substr(1))}catch(c){return null}},I=function(b,a){var c=null,d=[];if(e(b))for(c in b)b.hasOwnProperty(c)&&"function"!==typeof b[c]&&null!==b[c]&&d.push(C(c)+(e(a)?a:"=")+C(b[c]));return d.join("&")},J=function(b,a){var c=null;if(e(a)&&e(b))for(c in b)b.hasOwnProperty(c)&&e(a[c])&&(b[c]=a[c])},K=function(b,a,c){var d=b.split("."),f=d.length,h=2;if(e(a))h=a;else if(e(c)&&c)"com"!==d[f-1]&&(a=RegExp("^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$"),
4===f&&a.test(b)?h=4:2===d[f-1].length&&1<f&&"co"===d[f-2]&&(h=3));else if(2<d[f-1].length)h=2;else if(2===d[f-1].length)h=3;else return b;for(;d.length>h&&2<d.length;)d.shift();return d.join(".")},Y=function(b){if(window.self&&window.self.crypto&&window.self.crypto.getRandomValues){var a="_mch-"+b+"-";b=new Uint32Array(4);window.self.crypto.getRandomValues(b);b.forEach(function(b){a+=b.toString(16).padStart(8,"0")});return a}b="_mch-"+b+"-"+(new Date).getTime()+"-";var c;c=Math.floor(9E4*Math.random())+
1E4;return b+c},w=function(b){var a=l.cookie,c,d,f={id:null,token:null};b=C(b);f.store=function(a,c,d,f){var e=b+"="+I(this,":"),g=new Date;0<a?g.setTime(g.getTime()+864E5*a):g.setTime(g.getTime()-1);e+="; expires="+g.toGMTString();c&&(e+="; path="+c);d&&-1!==d.indexOf(".")&&(e+="; domain="+d);f&&(e+="; secure");l.cookie=e};if(""!==a)for(a=a.split(";"),c=0;c<a.length;c+=1)if(d=a[c].replace(/^\s+|\s+$/g,""),0===d.indexOf(b+"=")){a=d.substring(b.length+1);c=G(a);e(c.id)&&e(c.token)?J(f,c):J(f,G(a,":"));
break}return f},g={customName:null,notifyPrefix:null,wsInfo:null,altIds:[],visitorToken:null,cookieLifeDays:730,clickTime:350,cookieAnon:!0,mkt_tok:null,domainLevel:null,domainSelectorV2:!1,replayDetectLimit:5E3,httpsOnly:!1,asyncOnly:!1,useBeaconAPI:!0,anonymizeIP:!1,apiOnly:!1,externalSource:null,orgId:null,_ecid:null,_itpMitigationForAll:!1},m=null,n=null,Z=k.navigator.cookieEnabled||l.hasOwnProperty("cookie")&&(0<l.cookie.length||-1<(l.cookie="testcookie=test; max-age=10000").indexOf.call(l.cookie,
"testcookie=test;")),z=!1,A=[],L=null,$=function(b,a,c){var d=new k.XMLHttpRequest;d.open("GET",b,!0!==a);d.onreadystatechange=function(){2<=d.readyState&&d.abort()};if(a)try{d.timeout=c}catch(f){}try{d.send()}catch(e){}},Q=function(b,a,c,d,f){b=b+a+"&"+I(c)+"&"+I(d);g.useBeaconAPI&&window.navigator&&window.navigator.sendBeacon?window.navigator.sendBeacon(b):(c=(new Date).getTime(),f=!f&&!g.asyncOnly,0===a.indexOf("webevents/visitWebPage?")&&(f=!1),X?$(b,f,g.clickTime):(new k.Image(1,1)).src=b,L=
c+g.clickTime)},aa=function(){var b;return function(a,c){var d={x:a.clientX,y:a.clientY,el:c,time:(new Date).getTime()};if(e(b)&&d.x===b.x&&d.y===b.y&&d.el===b.el&&d.time<b.time+g.replayDetectLimit)return!0;b=d;return!1}}(),R=function(){var b=l.getElementsByName("_mkt_trk"),a=0,c="";e(n)&&(c="id:"+n.id+"&token:"+n.token);for(a=0;a<b.length;a+=1)"hidden"===b[a].type&&(b[a].value=c)},x=function(b,a,c,d){var f=null,h;h=q.hostname;var l=q.protocol,p="webevents/"+b;if(z){var k;if(k=window.navigator)a:{k=
window.navigator.userAgent;if("string"===typeof k&&k){if(0<=k.indexOf("AdsBot")||0<=k.indexOf("Wget")||0<=k.indexOf("msnbot")){k=!0;break a}if(0<=k.indexOf("Mozilla")&&(0<=k.indexOf("slurp")||0<=k.indexOf("bot"))){k=!0;break a}}k=!1}if(!k&&e(n)&&(a._mchId=n.id,a._mchTk=n.token,e(g.mkt_tok)&&(a.mkt_tok=g.mkt_tok),e(g.wsInfo)&&(a._mchWs=g.wsInfo),"clickLink"===b&&(a._mchCn=e(g.customName)?g.customName:""),a._mchHo=h,a._mchPo=q.port,e(a._mchRu)||(a._mchRu=s(q.pathname)),a._mchPc=l,a._mchVr="165",e(h)&&
0!==h.length&&"file:"!==l))for(f in g.anonymizeIP&&(a.aip=1),e(g.externalSource)&&(a._mchEs=g.externalSource),e(u)&&(a._mchEcid=u),p+="?_mchNc="+(new Date).getTime(),Q(g.notifyPrefix,p,a,c,d),g.altIds)g.altIds.hasOwnProperty(f)&&(h=g.altIds[f],a._mchId=h,Q(g.notifyPrefix.replace(/\w{3}\-\w{3}\-\w{3}\.mktoresp\.com/i,h+".mktoresp.com"),p,a,c,d))}else A.push(["post",arguments])},S=function(b){var a=b||k.event,c=a.target||a.srcElement,d={},f;f=a.which;var h=a.button;f=e(f)&&(1===f||2===f)||e(h)&&(0===
h||1===h||4===h)?!0:!1;if(f&&!a._mchDone){a._mchDone=!0;a=c;f=q.href||q;for(-1<f.indexOf("#")&&(f=f.substring(0,f.indexOf("#")));"A"!==a.tagName&&"AREA"!==a.tagName&&e(a.parentNode);)a=a.parentNode;a===l||a===k||"A"!==a.tagName&&"AREA"!==a.tagName?a=null:(c=a.href.replace(/^\s+|\s+$/g,""),a=e(c)&&0<c.length&&0!==c.indexOf("#")&&0!==c.indexOf(f+"#")&&0!==c.indexOf("javascript")&&!F(a,"mchNoDecorate")?a:null);e(a)&&!aa(b,a)&&(d._mchHr=s(a.href),x("clickLink",d),k.mktoLinkTarget=a.href)}},B=function(b){if(z){if(null!==
n)return n;var a=K(q.hostname,g.domainLevel,g.domainSelectorV2),c=w("_mkto_trk"),d=!1!==g.httpsOnly;if(e(c.id)||g.cookieAnon||b){if(c.id=m,e(c.token)||(e(g.visitorToken)&&"VISITOR_MKTTOK_REPLACE"!==g.visitorToken?c.token=g.visitorToken:c.token=Y(a)),c.store(g.cookieLifeDays,"/",a,d),d&&(c=w("_mkto_trk")),!d||e(c.id))return n=c,R(),c}else return null}else A.push(["createTrackingCookie",arguments])},T=function(){B(!0)},ba=function(b){var a=b.onclick;b.onclick="function"===typeof a?function(){T.apply(b,
arguments);return a.apply(b,arguments)}:T},M=function(b){var a=K(q.hostname,g.domainLevel,g.domainSelectorV2),c=w("mkto_opt_out"),d=!1!==g.httpsOnly;b?(c.id=!0,c.store(730,"/",a,d),b=w("_mkto_trk"),b.id&&b.store(0,"/",a,d)):c.store(0,"/",a,d)},U=function(){y&&e(t)&&D?window.fetch("https://"+t+"/getCookie?_mchId="+m+"&_mchTd="+r,{credentials:"include"}).then(function(b){window.localStorage.setItem("_mktoGetCookie_"+m+"_"+r,Date.now());if(b.ok)return b.body;throw Error("status ${response.status}");
})["catch"](function(b){window.console.warn("getCookie failed - ",b);window.localStorage.removeItem("_mktoLpDomain_"+m+"_"+r);window.localStorage.removeItem("_mktoSecureLp_"+m);window.localStorage.removeItem("_mktoGetCookie_"+m+"_"+r);t=null})["finally"](N):N()},O=function(b){try{var a=decodeURIComponent(b).replace(/_/g,"/").replace(/-/g,"+"),c=atob(a);b=[];for(a=0;a<c.length;a++)b.push(c.charCodeAt(a));if(2<=b.length&&10===b[0]){for(var a=c=0,d=1;d<b.length;){var f=b[d++],c=c|(f&127)<<a;if(0===(f&
128))break;a+=7;if(28<a)return null}if(b.length>=d+c){var e=b.slice(d,d+c),f="";for(b=0;b<e.length;b++)f+=String.fromCharCode(e[b]);return f}}}catch(g){}return null},V=function(b){for(var a=[],c=/kndctr_([A-Za-z0-9-]+)_AdobeOrg_identity=([^;]+)/g,d=/kndctr_([A-Za-z0-9-]+)_AdobeOrg_cluster=([^;]+)/g,f=l.cookie,h,g={};null!==(h=d.exec(f));)g[h[1]+"@AdobeOrg"]=decodeURIComponent(h[2]);for(;null!==(h=c.exec(f));)d=h[1]+"@AdobeOrg",e(b)&&d!==b||(h=O(h[2]))&&a.push(d+":"+(g[d]||"")+":"+h);return a.join(";")},
O=function(b){try{var a=decodeURIComponent(b).replace(/_/g,"/").replace(/-/g,"+"),c=atob(a);b=[];for(a=0;a<c.length;a++)b.push(c.charCodeAt(a));if(2<=b.length&&10===b[0]){for(var a=c=0,d=1;d<b.length;){var f=b[d++],c=c|(f&127)<<a;if(0===(f&128))break;a+=7;if(28<a)return null}if(b.length>=d+c){var e=b.slice(d,d+c),f="";for(b=0;b<e.length;b++)f+=String.fromCharCode(e[b]);return f}}}catch(g){}return null},V=function(b){for(var a=[],c=/kndctr_([A-Za-z0-9-]+)_AdobeOrg_identity=([^;]+)/g,d=/kndctr_([A-Za-z0-9-]+)_AdobeOrg_cluster=([^;]+)/g,
f=l.cookie,g,k={};null!==(g=d.exec(f));)k[g[1]+"@AdobeOrg"]=decodeURIComponent(g[2]);for(;null!==(g=c.exec(f));)d=g[1]+"@AdobeOrg",e(b)&&d!==b||(g=O(g[2]))&&a.push(d+":"+(k[d]||"")+":"+g);return a.join(";")},N=function(){if(!z){z=!0;var b=B(e(g.mkt_tok)),a,c;c={};for(var d={};0<A.length;)switch(a=A.shift(),a[0]){case "createTrackingCookie":b=B.apply(l,a[1]);break;case "post":x.apply(l,a[1])}if(e(g._ecid))u=g._ecid;else a:{a=g.orgId;if(e(window.Visitor)&&e(a))try{var f=window.Visitor.getInstance(a);
if(e(f)){u=a+":"+f.getLocationHint()+":"+f.getMarketingCloudVisitorID();break a}}catch(h){}if(f=V(a))u=f;else{for(var f=RegExp("AMCV_([A-Za-z0-9]+%40AdobeOrg)=([^;]+)","g"),m,p=[];null!==(m=f.exec(l.cookie));){var r=decodeURIComponent(m[1]),n;e(a)&&r!==a||null===(n=/MCMID(%7C|\|)([^%\|]+)/.exec(m[2]))||(m=/MCAAMLH-[^%\|]+(%7C|\|)([0-9]+)/.exec(m[2]),p.push(r+":"+(e(m)?m[2]:"")+":"+n[2]))}u=p.join(";")}}if(e(b))g.apiOnly||(c._mchCn=e(g.customName)?g.customName:"",d._mchHa=s(q.hash),d._mchRe=s(l.referrer),
d._mchQp=s(q.search.substr(1).replace(/&/g,"__-__")),x("visitWebPage",c,d,!0));else if(!(g.cookieAnon||e(k.Mkto)&&e(k.Mkto.formSubmit))){b=[];c=l.forms;d=c.length;for(n=0;n<d;n+=1)if(F(c[n],"lpeRegForm"))for(f=c[n].elements,p=f.length,a=0;a<p;a+=1)"submit"!==f[a].type||F(f[a],"mchNoDecorate")||b.push(f[a]);for(c=0;c<b.length;c+=1)ba(b[c])}}},P={CLICK_LINK:"clickLink",VISIT_WEB_PAGE:"visitWebPage",init:function(b,a){if(Z&&e(b)&&0!==b.length){m=b;m=m.toUpperCase();var c="",d,f,h;d=H(k.location.toString());
var n=null;g.notifyPrefix=q.protocol+"//"+m+".mktoresp.com/";e(a)&&(window.console.debug('Munchkin.init("%s") options:',b,a),J(g,a));e(d)&&(e(d.mkt_tok)&&(g.mkt_tok=d.mkt_tok),e(d.lpview)&&(c=d.lpview),e(d.marketo_opt_out)&&(n=d.marketo_opt_out));if(!e(g.mkt_tok))if(d=H(l.referrer),e(d.mkt_tok))g.mkt_tok=d.mkt_tok;else if(e(d.enid)&&e(d.type))for(h in d)d.hasOwnProperty(h)&&"enid"!==h&&"type"!==h&&(-1<h.indexOf("mkt_tok")||-1<d[h].indexOf("mkt_tok"))&&(f=H(h+"="+d[h]),e(f.mkt_tok)&&(g.mkt_tok=f.mkt_tok));
if("preview"!==c||!/\/lpeditor\/preview$/.test(q.pathname)){if(null===n){if(c=w("mkto_opt_out"),e(c.id)){M(!0);return}}else{if("true"===n){M(!0);return}"false"===n&&M(!1)}h=window.navigator.userAgent.toLowerCase();c=-1<h.indexOf("safari");h=/ version\/([0-9]+.[0-9]+)/.exec(h);y=c&&h&&12.1<=parseFloat(h[1])||g._itpMitigationForAll;r=K(q.hostname,g.domainLevel,g.domainSelectorV2);t=window.localStorage.getItem("_mktoLpDomain_"+m+"_"+r);e(t)&&-1<l.cookie.indexOf("_mkto_trk=")&&(c=window.localStorage.getItem("_mktoGetCookie_"+
m+"_"+r))&&828E5>Date.now()-c&&(y=!1);y&&window.fetch?(D="true"===window.localStorage.getItem("_mktoSecureLp_"+m),e(t)?U():window.fetch(q.protocol+"//"+m+".mktoutil.com/mktoutil/lpDomain?_mchId="+m+"&_mchTd="+r).then(function(a){if(a.ok)return a.json();throw Error("status ${response.status}");})["catch"](function(a){window.console.warn("getLpDomain failed - ",a)}).then(function(a){e(a)&&e(a.domain)&&(window.localStorage.setItem("_mktoLpDomain_"+m+"_"+r,t=a.domain),window.localStorage.setItem("_mktoSecureLp_"+
m,D=a.isSecure))})["finally"](U)):N()}}},munchkinFunction:function(b,a){var c={},d={};switch(b){case "clickLink":e(a.href)&&(c._mchHr=c._mchLr=a.href,x("clickLink",c));break;case "visitWebPage":e(a.url)&&(c._mchRu=a.url),e(a.params)&&(c._mchQp=a.params),e(a.name)&&(c._mchCn=a.name),d._mchRe=s(l.referrer),x("visitWebPage",c,d)}},createTrackingCookie:function(b){B(b)}};Date.prototype.getTimeAlias=Date.prototype.getTime;v(k,"beforeunload",function(){if(k.mktoLinkTarget&&(k.mktoLinkTarget.toLowerCase().startsWith("mailto:")||
k.mktoLinkTarget.toLowerCase().startsWith("tel:")))delete k.mktoLinkTarget;else{for(var b;0<E.length;)b=E.shift(),W.apply(this,b);if(e(L)){do b=new Date;while(b.getTimeAlias()<L)}}});v(l,"click",S,!0);(function(b){var a=!1,c=!0,d=l.documentElement,e=function(c){"readystatechange"===c.type&&"complete"!==l.readyState||a||(a=!0,b.call(k,c.type||c))},g=null,g=function(){try{d.doScroll("left")}catch(a){k.setTimeout(g,50);return}e("poll")};if("complete"===l.readyState)b.call(k,"lazy");else{if(l.createEventObject&&
d.doScroll){try{c=!k.frameElement}catch(m){}c&&g()}v(l,"DOMContentLoaded",e);v(l,"readystatechange",e);v(k,"load",e)}})(function(){R();var b=0;if(e(l.links))for(b=0;b<l.links.length;b+=1)v(l.links[b],"click",S,!0)});k.MunchkinTracker=k.Munchkin=P;k.mktoMunchkin=P.init;k.mktoMunchkinFunction=P.munchkinFunction}})(window);
